name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      aws:
        image: "localstack/localstack"
        ports:
          - 4566

      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 1s
          --health-timeout 2s
          --health-retries 10

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651
        with:
          ruby-version: "4.0.1"
          bundler-cache: true

      - name: Install Rubocop
        run: |
          gem install rubocop
          gem install rubocop-minitest
          gem install rubocop-performance

      - name: Run Rubocop
        run: rubocop --except Metrics

      - name: Setup AWS
        env:
          GIKI_ENV: production
          GIKI_CI: true
          AWS_PORT: ${{ job.services.aws.ports['4566'] }}
        run: |
          bundle exec setup_giki_config
          bundle exec setup_giki_local_aws

      - name: Run tests
        env:
          GIKI_ENV: production
          GIKI_CI: true
          AWS_PORT: ${{ job.services.aws.ports['4566'] }}
        run: bundle exec rake test
